#!/usr/bin/env bash

function ask() {
  printf "$* (Y/n)"
  local answer && read answer
  case $answer in
    [yY] | [yY]es | YES ) return 0 ;;
    * ) return 1 ;;
  esac
}

# Apt packages
if ask "apt install, install, install...?"; then
    sudo apt update && apt upgrade
    sudo apt --version
    case $HOSTNAME in 
      rodman | lebron )
        echo "road scripts/pkg-list-wsl..."
        sudo apt install $(cat ~/dotfiles/scripts/pkg-list-wsl) ;;
      * )
        echo "road scripts/pkg-list-debian..."
        sudo apt install $(cat ~/dotfiles/scripts/pkg-list-debian) ;;
    esac
fi

# Symlinks
if ask "dotfiles link, link, link...?"; then
  ~/dotfiles/scripts/symlinks
fi

# Git config
if ask "Git config?"; then
  git config --global user.name kottn
  git config --global user.email 35750723+kottn@users.noreply.github.com
  git config --global core.editor 'vim -c "set fenc=utf-8"'
  git config --global color.diff auto
  git config --global color.status auto
  git config --global color.branch auto
  git config --global core.pager "less -cm"
  git config --global core.quotepath false
fi

# Git clone
if ask "Git clone, clone, clone...?"; then
  mkdir -p ~/share && cd ~/share
  git clone $(cat ~/dotfiles/scripts/git-clone-list)
fi

