#!/usr/bin/env bash
function ask() {
  printf "$* (Y/n)"
  local answer && read answer
  case $answer in
    [yY] | [yY]es | YES ) return 0 ;;
    * ) return 1 ;;
  esac
}

getos=$(${HOME}/dotfiles/scripts/getos)

# Apt packages
if [[ ${getos} == debian ]]; then
  if ask "apt install, install, install...?"; then
      sudo apt update && sudo apt upgrade
      sudo apt --version
      if [[ $(uname -r) =~ Microsoft ]] ; then
          echo "road scripts/lst-pkg_wsl..."
          sudo apt install $(cat ~/dotfiles/scripts/lst-pkg_wsl)
      elif [[ $(uname -r) =~ amd64 ]] ; then
          echo "road scripts/lst-pkg..."
          sudo apt install $(cat ~/dotfiles/scripts/lst-pkg)
      fi
  fi
fi

# Symlinks
if ask "dotfiles link, link, link...?"; then
  ~/dotfiles/scripts/symlinks
  mkdir -p ~/.screen/sockets/; chmod 700 ~/.screen/sockets/
fi

# Git config
if ask "Git config?"; then
  git config --global user.name kottn
  git config --global user.email 35750723+kottn@users.noreply.github.com
  git config --global core.editor 'vim -c "set fenc=utf-8"'
  git config --global color.diff auto
  git config --global color.status auto
  git config --global color.branch auto
  git config --global core.pager "less -cm"
  git config --global core.quotepath false
  git config --global core.whitespace cr-at-eol
fi

# local
if ask "Make ~/local/* ?"; then
  mkdir -p ~/local/bin
  mkdir -p ~/local/kottn
  mkdir -p ~/local/share
fi

# etc
mkdir -p ~/_gm

