#!/usr/bin/env bash

cd ~/dotfiles

mkdir -p vim/backup
mkdir -p vim/viminfo

rURL=https://raw.githubusercontent.com

echo ""
echo " --- Now downloading..."
# -- git-completion
curl -LO ${rURL}/git/git/master/contrib/completion/git-completion.bash
curl -LO ${rURL}/git/git/master/contrib/completion/git-prompt.sh
# -- cdhist
curl -LO ${rURL}/euske/settings/master/bash/cdhist.sh
# -- vim-plug
mkdir -p vim/autoload
curl -L  ${rURL}/junegunn/vim-plug/master/plug.vim > vim/autoload/plug.vim

echo ""
echo " --- Now linking..."
for f in *; do
    [ "$f" = ".git" ] && continue
    [ "$f" = ".gitignore" ] && continue
    [ "$f" = "README.md" ] && continue
    [ "$f" = "Makefile" ] && continue
    ln -snfv ~/dotfiles/"$f" ~/."$f"
done

